name: Javadocs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  javadocs:
    name: Javadocs
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: main
          java-version: 17
          project: maven
          custom-command: javadoc -d javadoc -sourcepath ngrok-java/src/main/java/com/ngrok -sourcepath ngrok-java-native/src/main/java/com/ngrok -subpackages .
